name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: /opt/hostedtoolcache/node/14.20.1/x64/bin/npm install --cache /tmp/empty-cache && /opt/hostedtoolcache/node/14.20.1/x64/bin/npm cache verify && /opt/hostedtoolcache/node/14.20.1/x64/bin/npm install
        name: Build
      - run: /opt/hostedtoolcache/node/14.20.1/x64/bin/npm run test
        env:
          CI: true

  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Publish
        run: |
          /opt/hostedtoolcache/node/14.20.1/x64/bin/npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          /opt/hostedtoolcache/node/14.20.1/x64/bin/npm publish --public --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
